### ISSUE TITLE
[BUG] `jake` doesn't play nicely on Windows

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/jake#156]
Discovered during https://github.com/sonatype-nexus-community/jake/actions/runs/11860011104/job/33054310974

All Windows builds fail with:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\a\jake\jake\jake\app.py", line 106, in main
    JakeCmd(args).execute()
  File "D:\a\jake\jake\jake\app.py", line 80, in execute
    exit_code: int = command.execute(arguments=self._arguments)
  File "D:\a\jake\jake\jake\command\__init__.py", line [44](https://github.com/sonatype-nexus-community/jake/actions/runs/11860011104/job/33054310974#step:13:45), in execute
    return self.handle_args()
  File "D:\a\jake\jake\jake\command\oss.py", line 56, in handle_args
    with Progress() as progress:
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\progress.py", line 1191, in __exit__
    self.stop()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\progress.py", line 1177, in stop
    self.live.stop()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\live.py", line 1[47](https://github.com/sonatype-nexus-community/jake/actions/runs/11860011104/job/33054310974#step:13:48), in stop
    with self.console:
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\console.py", line 2019, in _check_buffer
    self._write_buffer()
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\console.py", line 2055, in _write_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\jake-3HYq3Xz5-py3.10\lib\site-packages\rich\_win32_console.py", line 402, in write_text
    self.write(text)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\encodings\cp12[52](https://github.com/sonatype-nexus-community/jake/actions/runs/11860011104/job/33054310974#step:13:53).py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f40d' in position 0: character maps to <undefined>
Jake Version: 3.0.14
Put your Python dependencies in a chokehold
```

**Comment by DavidiBeMe** [comment]
I set PYTHONIOENCODING to "utf-8" and then I don't get this error anymore.   I know that Jakes header design looks cool, but I believe that that header is what is causing this issue.

**Comment by madpah** [comment]
We're going to replace the underlying ASCII art library in `jake 4.0.0` @DavidiBeMe which we believe will resolve this properly.

**Comment by madpah** [comment]
We've just published a release candidate for `jake 4.0.0`: https://pypi.org/project/jake/4.0.0rc1/

We'd love you try it out and see if you can find any bugs before we hit release. 🙏
