### ISSUE TITLE
[BUG] unexpected FIN and broken pipe through web proxy

### ISSUE THREAD

**Issue by awkmon** [sonatype-nexus-community/jake#34]
**Describe the bug**
I'm not sure that this is a bug. Has this been tested through an outbound web proxy?

jake ddt works flawlessly through standard gateways, but fails with broken pipe when executed through web proxy. 

**To Reproduce**
export http_proxy/https_proxy variables pointing to outbound web proxy.
conda list | jake ddt

**Expected behavior**
I expect it to scan and present vulnerabilities for all install modules (534). Instead, it lists 371 modules and no vulnerabilities.

**Screenshots**
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

 

    Traceback (most recent call last):

      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__

        return func(*args, **kwargs)

      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main

        exit_code = do_call(args, p)

      File "/opt/conda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call

        return getattr(module, func_name)(args, parser)

      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main_list.py", line 141, in execute

        exitcode = print_packages(prefix, regex, format, piplist=args.pip,

      File "/opt/conda/lib/python3.8/site-packages/conda/cli/main_list.py", line 85, in print_packages

        print('\n'.join(map(text_type, output)))

    BrokenPipeError: [Errno 32] Broken pipe

 

`$ /opt/conda/bin/conda list`

 

  environment variables:

                 CIO_TEST=<not set>

               CONDA_ROOT=/opt/conda

           CURL_CA_BUNDLE=<not set>

              HTTPS_PROXY=<set>

               HTTP_PROXY=<set>

                 NO_PROXY=<set>

                     PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.loca
                          l/bin:/home/ec2-user/bin:/opt/conda/bin

       REQUESTS_CA_BUNDLE=<not set>

            SSL_CERT_FILE=<not set>

               http_proxy=<set>

              https_proxy=<set>

                 no_proxy=<set>

 

     active environment : None

       user config file : /home/ec2-user/.condarc

populated config files : /home/ec2-user/.condarc

          conda version : 4.8.4

    conda-build version : 3.19.2

         python version : 3.8.2.final.0

       virtual packages : __glibc=2.26

       base environment : /opt/conda  (writable)

           channel URLs : http://x.x.x.x/condarepo/linux-64

                          http://x.x.x.x/condarepo/noarch

          package cache : /opt/conda/pkgs

                          /home/ec2-user/.conda/pkgs

       envs directories : /opt/conda/envs

                          /home/ec2-user/.conda/envs

               platform : linux-64

             user-agent : conda/4.8.4 requests/2.23.0 CPython/3.8.2 Linux/4.14.186-146.268.amzn2.x86_64 amzn/2 glibc/2.26

                UID:GID : 1000:1000

             netrc file : None

           offline mode : False

 

 

An unexpected error has occurred. Conda has prepared the above report.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Amazon Linux 2
 - Python Version: [e.g. 3.7.6]  3.8.2
 - Version [e.g. 22] 0.2.24

**Additional context**
Appears to be a code issue, but unsure. tcpdump seems to exonerate the proxy.

**Comment by awkmon** [comment]
I completely reinstalled and updated conda and this is working now. I don't think it was jake issue, but rather a conda issue.
