### ISSUE TITLE
[BUG] Missing attribute  generating report in version 1.4 in JSON format, an attribute is missing.

### ISSUE THREAD

**Issue by damiencarol** [sonatype-nexus-community/jake#91]
When generating report in version 1.4 in JSON format, an attribute is missing in the components data.

According to the specification of CycloneDX a vulnerability reference a component by his bom-ref. So the components should have bom-ref.

My advice is to use the PURL string as a bom-ref

![image](https://user-images.githubusercontent.com/1694940/150698937-29eed4ea-b12b-4469-8b8a-58d80e3935c2.png)

Renamed with txt because github
[jake.json.txt](https://github.com/sonatype-nexus-community/jake/files/7921491/jake.json.txt)

## Version

- Python 3.9
- Jake 1.4.0
- cmd `jake ddt --output-format cyclonedx-json --schema-version 1.4 -o ~/dd2/jake.json`

**Comment by madpah** [comment]
Hi @damiencarol - thanks for the report.

Can you please confirm a few things:
- Python Version
- Jake Version
- Full command invoked

Thanks

**Comment by damiencarol** [comment]
added some details in the description

**Comment by madpah** [comment]
@damiencarol - `1.4.1` has been released - can you test with that please and let us know?

**Comment by damiencarol** [comment]
Seems it broke my command:

```
(.venv2) [damien@damien vulnerabilities]$ python3 -m pip install jake==1.4.1
Collecting jake==1.4.1
  Using cached jake-1.4.1-py3-none-any.whl (28 kB)
Requirement already satisfied: polling2>=0.5.0 in ./.venv2/lib/python3.10/site-packages (from jake==1.4.1) (0.5.0)
Collecting cyclonedx-bom<3.0.0,>=2.0.1
  Using cached cyclonedx_bom-2.0.1-py3-none-any.whl (25 kB)
Requirement already satisfied: pyfiglet>=0.8.post1 in ./.venv2/lib/python3.10/site-packages (from jake==1.4.1) (0.8.post1)
Requirement already satisfied: ossindex-lib>=0.2.1 in ./.venv2/lib/python3.10/site-packages (from jake==1.4.1) (0.2.1)
Requirement already satisfied: rich>=10.15.2 in ./.venv2/lib/python3.10/site-packages (from jake==1.4.1) (11.0.0)
Requirement already satisfied: requests in ./.venv2/lib/python3.10/site-packages (from jake==1.4.1) (2.27.1)
Collecting cyclonedx-python-lib<2.0.0,>=1.3.0
  Using cached cyclonedx_python_lib-1.3.0-py3-none-any.whl (168 kB)
Requirement already satisfied: types-setuptools>=57.0.0 in ./.venv2/lib/python3.10/site-packages (from cyclonedx-python-lib<2.0.0,>=1.3.0->cyclonedx-bom<3.0.0,>=2.0.1->jake==1.4.1) (57.4.4)
Requirement already satisfied: packageurl-python>=0.9 in ./.venv2/lib/python3.10/site-packages (from cyclonedx-python-lib<2.0.0,>=1.3.0->cyclonedx-bom<3.0.0,>=2.0.1->jake==1.4.1) (0.9.6)
Requirement already satisfied: types-toml<0.11.0,>=0.10.0 in ./.venv2/lib/python3.10/site-packages (from cyclonedx-python-lib<2.0.0,>=1.3.0->cyclonedx-bom<3.0.0,>=2.0.1->jake==1.4.1) (0.10.1)
Requirement already satisfied: toml<0.11.0,>=0.10.0 in ./.venv2/lib/python3.10/site-packages (from cyclonedx-python-lib<2.0.0,>=1.3.0->cyclonedx-bom<3.0.0,>=2.0.1->jake==1.4.1) (0.10.2)
Requirement already satisfied: setuptools>=47.0.0 in ./.venv2/lib/python3.10/site-packages (from cyclonedx-python-lib<2.0.0,>=1.3.0->cyclonedx-bom<3.0.0,>=2.0.1->jake==1.4.1) (58.1.0)
Requirement already satisfied: tinydb<5.0.0,>=4.5.1 in ./.venv2/lib/python3.10/site-packages (from ossindex-lib>=0.2.1->jake==1.4.1) (4.6.1)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv2/lib/python3.10/site-packages (from requests->jake==1.4.1) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.venv2/lib/python3.10/site-packages (from requests->jake==1.4.1) (1.26.8)
Requirement already satisfied: idna<4,>=2.5 in ./.venv2/lib/python3.10/site-packages (from requests->jake==1.4.1) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./.venv2/lib/python3.10/site-packages (from requests->jake==1.4.1) (2.0.10)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./.venv2/lib/python3.10/site-packages (from rich>=10.15.2->jake==1.4.1) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in ./.venv2/lib/python3.10/site-packages (from rich>=10.15.2->jake==1.4.1) (0.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./.venv2/lib/python3.10/site-packages (from rich>=10.15.2->jake==1.4.1) (2.11.2)
Installing collected packages: cyclonedx-python-lib, cyclonedx-bom, jake
  Attempting uninstall: cyclonedx-python-lib
    Found existing installation: cyclonedx-python-lib 1.1.1
    Uninstalling cyclonedx-python-lib-1.1.1:
      Successfully uninstalled cyclonedx-python-lib-1.1.1
  Attempting uninstall: cyclonedx-bom
    Found existing installation: cyclonedx-bom 2.0.0
    Uninstalling cyclonedx-bom-2.0.0:
      Successfully uninstalled cyclonedx-bom-2.0.0
  Attempting uninstall: jake
    Found existing installation: jake 1.4.0
    Uninstalling jake-1.4.0:
      Successfully uninstalled jake-1.4.0
Successfully installed cyclonedx-bom-2.0.1 cyclonedx-python-lib-1.3.0 jake-1.4.1
(.venv2) [damien@damien vulnerabilities]$ jake ddt  -o ~/dd2/unittests/scans/cyclonedx/jake2.json --output-format json --schema-version 1.4 
                   ___           ___           ___     
       ___        /  /\         /  /\         /  /\    
      /__/\      /  /::\       /  /:/        /  /::\   
      \__\:\    /  /:/\:\     /  /:/        /  /:/\:\  
  ___ /  /::\  /  /::\ \:\   /  /::\____   /  /::\ \:\ 
 /__/\  /:/\/ /__/:/\:\_\:\ /__/:/\:::::\ /__/:/\:\ \:\
 \  \:\/:/~~  \__\/  \:\/:/ \__\/~|:|~~~~ \  \:\ \:\_\/
  \  \::/          \__\::/     |  |:|      \  \:\ \:\  
   \__\/           /  /:/      |  |:|       \  \:\_\/  
                  /__/:/       |__|:|        \  \:\    
                  \__\/         \__\|         \__\/    

                                                  
            /)                     /)             
        _/_(/    _     _  __   _  (/_   _         
 o   o  (__/ )__(/_   /_)_/ (_(_(_/(___(/_ o   o  
                                                  
                                                  

Jake Version: 1.4.1
Put your Python dependencies in a chokehold

🐍 Collected 28 packages from your environment  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Querying OSS Index for details on your packages ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  30% -:--:--
Sanity checking...                              ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/home/damien/vulnerabilities/.venv2/bin/jake", line 8, in <module>
    sys.exit(main())
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/jake/app.py", line 124, in main
    JakeCmd().execute()
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/jake/app.py", line 69, in execute
    exit_code: int = command.execute(arguments=self._arguments)
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/jake/command/__init__.py", line 45, in execute
    return self.handle_args()
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/jake/command/oss.py", line 78, in handle_args
    oss_index_results = oss.get_component_report(
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/ossindex/ossindex.py", line 59, in get_component_report
    return self._get_results(packages=packages)
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/ossindex/ossindex.py", line 146, in _get_results
    results = results + self._make_oss_index_component_report_call(packages=chunk)
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/ossindex/ossindex.py", line 163, in _make_oss_index_component_report_call
    self._upsert_cache_with_oss_index_responses(oss_components=results)
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/ossindex/ossindex.py", line 187, in _upsert_cache_with_oss_index_responses
    self._cache_database.update({
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/tinydb/table.py", line 385, in update
    self._update_table(updater)
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/tinydb/table.py", line 725, in _update_table
    updater(table)
  File "/home/damien/vulnerabilities/.venv2/lib/python3.10/site-packages/tinydb/table.py", line 377, in updater
    if _cond(table[doc_id]):
TypeError: 'int' object is not callable
```

**Comment by damiencarol** [comment]
Is there a way to wipe-out data from previous runs?

**Comment by damiencarol** [comment]
The link between the vulnerability and the component is good now. :+1: 
But I just found a new bug, creating a new issue => #93  .
